### ISSUE TITLE
Crash with samples/shooter_tutorial/tut_coro.lobster

### ISSUE THREAD

**Issue by GrundleTrundle** [aardappel/lobster#20]
I'm using the lastest commit from master, on x64 linux, compiled to 32 bit. (FWIW, I get the same result compiled to 64 bit as well).   gcc (GCC) 6.2.1 20160830  

When I run the tut_cor.lobster sample, the menu comes up, but when I hit space to play, the process dies with a segfault.   In the stack trace below, curcoroutine == 0.

```
Thread 1 "lobster_cmake" received signal SIGSEGV, Segmentation fault.
0x08251947 in lobster::VM::CoClean (this=0x8506040) at /home/pkelley/src/lobster/dev/src/vm.cpp:565
565         for (int i = 1; i <= *curcoroutine->varip; i++) {
(gdb) print i
$1 = 1
(gdb) print curcoroutine
$2 = (lobster::CoRoutine *) 0x0
(gdb) bt
#0  0x08251947 in lobster::VM::CoClean (this=0x8506040) at /home/pkelley/src/lobster/dev/src/vm.cpp:565
#1  0x0825961d in lobster::VM::F_COEND (this=0x8506040) at /home/pkelley/src/lobster/dev/src/vm.cpp:1246
#2  0x0825977b in lobster::VM::EvalProgram (this=0x8506040) at /home/pkelley/src/lobster/dev/src/vm.cpp:1310
#3  0x0825ee1e in lobster::RunBytecode(char const*, std::vector<unsigned char, std::allocator<unsigned char> >&&, void const*, void const*) (programname=0x8505bf8 "tut_coro.lobster", 
    bytecode=<unknown type in /home/pkelley/src/lobster/lobster/lobster_cmake, CU 0x42bf28, DIE 0x450799>, entry_point=0x0, static_bytecode=0x0) at /home/pkelley/src/lobster/dev/src/vm.cpp:1553
#4  0x08248e21 in EngineRunByteCode(char const*, std::vector<unsigned char, std::allocator<unsigned char> >&&, void const*, void const*) (fn=0xffffdd24 "samples/shooter_tutorial/tut_coro.lobster", 
    bytecode=<unknown type in /home/pkelley/src/lobster/lobster/lobster_cmake, CU 0x3d69e1, DIE 0x3f3464>, entry_point=0x0, static_bytecode=0x0) at /home/pkelley/src/lobster/dev/src/sdlsystem.cpp:678
#5  0x08228872 in main (argc=2, argv=0xffffdbc4) at /home/pkelley/src/lobster/dev/src/main.cpp:129
(gdb) bt full
#0  0x08251947 in lobster::VM::CoClean (this=0x8506040) at /home/pkelley/src/lobster/dev/src/vm.cpp:565
        i = 1
        co = 0x8528c20
#1  0x0825961d in lobster::VM::F_COEND (this=0x8506040) at /home/pkelley/src/lobster/dev/src/vm.cpp:1246
No locals.
#2  0x0825977b in lobster::VM::EvalProgram (this=0x8506040) at /home/pkelley/src/lobster/dev/src/vm.cpp:1310
        op = 126
#3  0x0825ee1e in lobster::RunBytecode(char const*, std::vector<unsigned char, std::allocator<unsigned char> >&&, void const*, void const*) (programname=0x8505bf8 "tut_coro.lobster", 
    bytecode=<unknown type in /home/pkelley/src/lobster/lobster/lobster_cmake, CU 0x42bf28, DIE 0x450799>, entry_point=0x0, static_bytecode=0x0) at /home/pkelley/src/lobster/dev/src/vm.cpp:1553
No locals.
#4  0x08248e21 in EngineRunByteCode(char const*, std::vector<unsigned char, std::allocator<unsigned char> >&&, void const*, void const*) (fn=0xffffdd24 "samples/shooter_tutorial/tut_coro.lobster", 
    bytecode=<unknown type in /home/pkelley/src/lobster/lobster/lobster_cmake, CU 0x3d69e1, DIE 0x3f3464>, entry_point=0x0, static_bytecode=0x0) at /home/pkelley/src/lobster/dev/src/sdlsystem.cpp:678
No locals.
#5  0x08228872 in main (argc=2, argv=0xffffdbc4) at /home/pkelley/src/lobster/dev/src/main.cpp:129
        parsedump = false
        default_bcf = 0x83f77e9 "default.lbc"
        bcf = 0x0
        fn = 0xffffdd24 "samples/shooter_tutorial/tut_coro.lobster"
        helptext = {static npos = 4294967295, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x85058f0 "\nUsage:\nlobster [ OPTIONS ] [ FILE ]\nCompile & run FILE, or omit FILE to load default.lbc\n-w", ' ' <repeats 21 times>, "Wait for input before exiting.\n-b", ' ' <repeats 21 times>, "Compile to bytecode file, don't r"...}, 
          _M_string_length = 688, {_M_local_buf = "\260\002\000\000\000\000\000\000X\332\377\377G\224$\b", _M_allocated_capacity = 688}}
        disasm = false
        to_cpp = false
        bytecode = {<std::_Vector_base<unsigned char, std::allocator<unsigned char> >> = {_M_impl = {<std::allocator<unsigned char>> = {<__gnu_cxx::new_allocator<unsigned char>> = {<No data fields>}, <No data fields>}, _M_start = 0x0, _M_finish = 0x0, 
              _M_end_of_storage = 0x0}}, <No data fields>}
        wait = false
        from_bundle = false

```

**Comment by aardappel** [comment]
Hi, thanks for reporting! Looks like there were 2 problems that were uncovered by recent code-refactorings. I fixed them both here: https://github.com/aardappel/lobster/commit/8c2df763b32b850bc3adc2002f7af5f851325506

Let me know if now runs well for you.

**Comment by GrundleTrundle** [comment]
It works now.  Thanks for the fix.
